Add extra headers in the requests
MaibornWolff/dd-import pull request #101
Opened 2023-07-22 19:09 UTC by gtzsec

I added 2 additional optional HEADERS,

DD_EXTRA_HEADER_1
DD_EXTRA_HEADER_1_VALUE
DD_EXTRA_HEADER_2
DD_EXTRA_HEADER_2_VALUE

 Sometimes Defect Dojo will be behind some sort of WAF or Zero Trust solution, this requires to set some extra authentication tokens before actually reaching Defect Dojo

2023-08-05 19:10 UTC, gtzsec commented
@StefanFl can you please check this out :3

2023-08-06 17:49 UTC, StefanFl commented
Sorry @gtzsec, have been quite busy the last weeks. I just merged to other PRs, there are 2 conflicts now. Can you please resolve them? And please add the additional headers in the unit tests.

2023-08-10 04:15 UTC, gtzsec commented
@StefanFl ready!

2023-08-10 19:40 UTC, StefanFl requested changes
Unfortunately you haven't resolved the conflict properly, so the table has double entries and some lines are missing in section that prints the environment variables.

2023-08-10 19:40 UTC, StefanFl commented on dd_import/environment.py
> -        print('DD_CLOSE_OLD_FINDINGS_PRODUCT_SCOPE:', self.close_old_findings_product_scope)
This line will be deleted by your changes.

2023-08-10 19:40 UTC, StefanFl commented on dd_import/environment.py
> -        print('DD_DO_NOT_REACTIVATE:               ', self.do_not_reactivate)
This line will be deleted by your changes.

2023-08-10 19:40 UTC, StefanFl commented on dd_import/environment.py
> -        print('DD_SOURCE_CODE_MANAGEMENT_URI:      ', self.source_code_management_uri)
This line will be deleted by your changes.

2023-08-10 19:40 UTC, StefanFl commented on README.md
> +<<<<<<< HEAD
This is a remain of the conflict and needs to be deleted

2023-08-10 19:40 UTC, StefanFl commented on README.md
> +=======
This is a remain of the conflict and needs to be deleted

2023-08-10 19:40 UTC, StefanFl commented on README.md
> +>>>>>>> main
This is a remain of the conflict and needs to be deleted

2023-08-10 19:40 UTC, StefanFl commented on README.md
>  | Parameter                           | Re-import findings | Import languages | Remark                                                                                            |
Here the table starts again. The conflict has not been removed properly, now there are the old and the new version of the table in the file.

2023-08-11 00:30 UTC, closed without merging

2023-08-11 02:10 UTC, gtzsec commented
I opened a new MR :)